### PR TITLE
Update dependencies, fix linter options and other details

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**

### CODE REVIEW

**Comment by ianperrin** [comment]
Hi @KristjanESPERANTO 

Thanks for the pull request.

Unfortunately, the changes are failing as the package name has been renamed. Can you revert the package name change and try again?

**Comment by KristjanESPERANTO** [comment]
Hi @ianperrin :slightly_smiling_face:
Capital letters are not allowed in the name in the `package.json`. I forgot to make the adjustment in the `package-lock.json` as well. I've done that now. The test should no longer get stuck at this point :smiley:

**Comment by ianperrin** [comment]
> Hi @ianperrin 🙂
> Capital letters are not allowed in the name in the `package.json`. I forgot to make the adjustment in the `package-lock.json` as well. I've done that now. The test should no longer get stuck at this point 😃

Understood.

Will anyone who has installed the module need to update their config file to use the lowercase name? If so this is a breaking change and will need mentioning in the [updating](https://github.com/ianperrin/MMM-Formula1/blob/master/README.md#updating) section and example corrected in the [Using the module](https://github.com/ianperrin/MMM-Formula1/blob/master/README.md#using-the-module) sections of the README.md 

Finally, sometime ago, I had created [tests/node_helper.test.js](https://github.com/ianperrin/MMM-Formula1/tree/master/tests/node_helper.test.js) with the intention of writing some tests for the module. For completeness, I believe the module name needs changing there too

**Comment by KristjanESPERANTO** [comment]
Users shouldn't even notice the change. I have corrected this in other modules without issues.

But the test process still hangs: `npm ERR! Cannot read property 'f1-api' of undefined`.

I would take a look at that in the next few days. Until then I'll put the PR on draft :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
The tests should now work :slightly_smiling_face: The module works with node 14, but the tests with node 14 fail. Since node 14 will be EOL next month, I thought we can omit the node 14 test  😅

**Comment by KristjanESPERANTO** [comment]
BTW: There is no breaking change.

**Comment by ianperrin** [comment]
Great thanks @KristjanESPERANTO

**Pull request merged**
